package com.jm.util;

public interface NameConst 
{
    public static String FONT_DEFAULT = "FONT_DEFAULT";
    public static final String MACRO_TABLE = "MACRO_TABLE";
    public static final String UTIL_TD = "td";
    public static String USER      ="USER";
    public static String SELF      ="self";
    public static String FUNCTION  ="FUNCTION";
    public static String ARGS      ="ARGS";
    public static String CLEAR     ="CLEAR";
    public static String RESULT    ="RESULT";
    public final String SERVER     ="server";
    public final String PORT       ="port";
    public final String QUIT       ="quit"; 
    public final String ERROR      ="error"; 
    public final String REGISTER   ="register"; 
  public final String NAMESERVER   ="nameserver"; 
  public final String COMMAND      ="Command";
  public final String QUERY        ="query";
  public final String HOST         ="host";
  public final String APP          ="app";
  public final String ALIVE        ="alive";
  public final String REMOVE       ="remove";
  public final String ALLHOST      ="allhost";
  public final String CHECKCALLBACK ="callback";
  public final String OK       ="ok";
  public final String EQ       ="=";
  public final String MYHOST   ="myhostname";
  public final String ALLNAME  ="all_name_host";
  public final String REGNSRV  ="reg_name_server";
  public final String ALLAPPHOST="all_app_host";
  public final String HOSTINFO ="hostinfo";
  public final String ADDPARAM ="add";
  public final String NEWPARAM ="new";
  public final String TABLE    ="table";
  public static final String NEW  = "new";
  public static final String NAME = "name";
  public static final String ADD = "add";
    public static final String ACTION = "action";
    public static final String VALUE = "value";
    public static final String FORM = "form";
    public static final String EVENT = "event";
    public static final String OUT = "out";
    public static final String KEY_ = "KEY_";
    public static final String DIALOG = "dialog";
    public static final String PROP = ".properties";
    public static final String PROCESS = "process";
    
    public static final String BEAN = "bean";
    public static final String EXTEND = "extend";
    public static final String BGGROUP = "bggroup";
    public static final String RADIO   = "radio";
    public static final String SET     = "set";
    public static final String GET     = "get";
    public final String CONFIG   ="com.csp.config";
    public final String TABLES   ="com.csp.tables";
    public final String DEFAULT  ="com.csp.default";
    public final String S_ONE      ="ONE";
    public final String S_TWO      ="TWO";
    public final String S_TWO_CHECK="TWO_CHECK";
    public final String S_TABLE    ="TABLE";
    public final String S_TYPE     ="type";
    public final String S_ITYPE    ="itype";
    public final String S_ARG      ="arg";
    public final String S_DATA     ="data";
    public final String SA_SOURCE   ="source";
    public final String PSEP       ="###";
    public final String REF        ="-->";
    public final String XNAME      ="__name";
}
